apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: managedkafkaconnections.rhoas.redhat.com
  annotations:
    service.binding/bootstrapServer: 'path={.status.bootstrapServer.host}'
    service.binding/password: >-
      path={.status.serviceAccountSecretName},objectType=Secret,sourceKey=client-secret
    service.binding/saslMechanism: 'path={.status.saslMechanism}'
    service.binding/securityProtocol: 'path={.status.securityProtocol}'
    service.binding/user: >-
      path={.status.rh-managed-services-api-accesstoken},objectType=Secret,sourceKey=client-id
spec:
  group: rhoas.redhat.com
  names:
    kind: ManagedKafkaConnection
    plural: managedkafkaconnections
    shortNames:
    - mkc
    singular: managedkafkaconnection
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            accessTokenSecretName:
              type: string
            kafkaId:
              type: string
            credentials:
              properties:
                serviceAccountSecretName:
                  type: string
              type: object
          type: object
        status:
          properties:
            message:
              type: string
            updated:
              type: string
            boostrapServer:
              properties:
                host:
                  type: string
              type: object
            serviceAccountSecretName:
              type: string
            saslMechanism:
              type: string
            securityProtocol:
              type: string
            conditions:
              type: array
              items:
                type: object
                properties:
                  type:
                    type: string
                  reason:
                    type: string
                  message:
                    type: string
                  status:
                    type: string
                  lastTransitionTime:
                    type: string
          type: object
      type: object
  versions:
  - name: v1alpha1
    served: true
    storage: true
  preserveUnknownFields: false
