apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: managedkafkaconnections.rhoas.redhat.com
  annotations:
    service.binding/host: 'path={.status.bootstrapServerHost}'
    service.binding/password: >-
      path={.status.serviceAccountSecretName},objectType=Secret,sourceKey=client-secret
    service.binding/user: >-
      path={.status.serviceAccountSecretName},objectType=Secret,sourceKey=client-id
    service.binding/saslMechanism: 'path={.status.saslMechanism}'
    service.binding/securityProtocol: 'path={.status.securityProtocol}'
spec:
  group: rhoas.redhat.com
  names:
    kind: ManagedKafkaConnection
    plural: managedkafkaconnections
    shortNames:
    - mkc
    singular: managedkafkaconnection
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              accessTokenSecretName:
                type: string
              kafkaId:
                type: string
              credentials:
                properties:
                  serviceAccountSecretName:
                    type: string
                type: object
            type: object
          status:
            properties:
              message:
                nullable: true
                type: string
              uiRef:
                nullable: true
                type: string
              updated:
                nullable: true
                type: string
              bootstrapServerHost:
                nullable: true
                type: string
              serviceAccountSecretName:
                nullable: true
                type: string
              saslMechanism:
                nullable: true
                type: string
              securityProtocol:
                nullable: true
                type: string
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    reason:
                      type: string
                    message:
                      type: string
                    status:
                      type: string
                    lastTransitionTime:
                      type: string
            type: object
        type: object
  preserveUnknownFields: false
